apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: prod
spec:
  encryptedData:
    password: AgC7vCt1QtoyAfGrB7DBXpHTazg8a+wHJR8EyF05OAjFd3dM03hx0C0Ygyo02SP+YHiIe1HVhsFkzaFR2MuQVARzAbHB9lZccbDzX4LDlccjbJ6VxUKUmmbWGjQCsZ/iHZCL5gXXzRAk60BtQkuJ5tJeFx3O910eAmpyc3DhjacYrJyIOmkgr1TTZT0zxudNKXqrFqU3kpP3ZOYTCFb6qTU7gzbXJUU5YDQoZm7qalljDO4ZSUvkQf5YrEJzvhGIIqXrcEPRscf041hqmWmwxH6r8WsThab4Pw8h2xi6EmaoDXNTRIRig0K6Xvhu7MGj7a6YINuaT/YtJ3xnXhfPZTCdBxrHNyQMeajqLNtw2qEuCFfbveZ5JGL3LKKHX39v2IlnsLCCrrXhHchsxJNeqcbRIF+7/0AcBHxG5sPiOpv46NSsnGuGhROdDQiwLFOxGYXxqQXSXS8oshAPv0ddvBfUKcez+R3sncSddqpyeODZ0toygIkPYqwu2T2BUvniOt2UWyjNYsXvGfxwgdNHAe966VXxVw4jnYMYMxK11hDSwvLFeRWD+P4xO5M14IRtTRAvjIvRL9ARmp2htiyouHFZg4RPYQ0klOxZT+BSD+esekPx1lmUeoaCxOP9RoRoVMVLOvzUxMMvU8cEvBvtnTip9braWm5JHWyQ3oWu81vKvTPOXSqIlcMgp/sZPYMNVI61ZH9Ygw==
    user: AgCh25De695LjJdEghtgSu/vNBBw9zX9mXx6It0C+sEhzar0Lx3k4scAItY6P06rYZTHfp0OT8oiYr9uwnxNHC+29UDm+aLImr6URYk2Cw0nk6wPfWnntHxHqe+FIs8uIxSm71IkxdYjGr+SDoyHaNZy4JfOrOzvrbN1fVJEEwP1KCynRhWkOMtXqxmBnw1jREoG9AirpfXhjs/s44JtZI3y/7T8yW0Wy9G5np+JWBmKLz8W3+BYiNH1qzrQgbK0zg55qQH86TAJAqwqPfapWyBx/iMNYtAnGufpfx3Gh43Mkzmgv4BztToB7lba0pw7tO16lIoSYLmYbnTc/JiykP4+CP/b3ysZHBPFqNFtLV9m+efP4NA+tK1L6FgbjyHCrddVH+OuJOdsLWnXZqekBtKkXYeP2duAPrDPBs97UBJXgZVHS7z8vDlq1BVmoThF7ZX+mSpwN6UAfOPoWAOpvSAa8dHx5pc22CMm7aUA+q7iDKMHplxBRNPpk7RiwZUmtqGlmc3is4EIwdD/5sb7XTBuXj0HpQKVvZdXnvGANxV3RcIMKGF8Z+mJI4ETZu7YIrptDtrYtpsvY/Wbwe5GF4R9WdUgFcOo4o9/ZbB5hlWrGfUlyO7uzjuLsrfEUtr0V3wrPQcI0UGM8yJmPGzQacTACQWwFmI0j5aD9PQSW6t6S6IpgRQ1lpk51gEYrvAwnUV5e01tkg==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: prod
status: {}

